import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { faker } from '@faker-js/faker';

function uuid() {
  return crypto.randomUUID();
}

function escapeSql(str: string | null | undefined): string {
  if (str == null) return 'NULL';
  return `'${str.replace(/'/g, "''")}'`;
}

const WOMENSWEAR_ID = 'eac8973b-40a2-4ffe-a50e-6ffd46d528eb';
const JEWELRY_ID = '19f28ebb-b54c-4cde-a88c-abce56190784';
const COLLECTION_ID = '18f8ab7a-9e04-4fe7-b943-7591ffb84da2'; // The Nairobi Edit

const womenswearNames = [
  'Satin Evening Dress',
  'Linen Wide-Leg Trousers',
  'Tailored Double-Breasted Blazer',
  'Silk Wrap Dress',
  'Classic White Shirt',
  'Pleated Midi Skirt',
  'Knit Lounge Set',
  'Structured Jumpsuit',
  'Cotton Poplin Maxi Dress',
  'Oversized Trench Coat'
];

const jewelryNames = [
  'Gold Hoop Earrings',
  'Pearl Drop Earrings',
  'Minimal Chain Necklace',
  'Layered Pendant Necklace',
  'Tennis Bracelet',
  'Gold Bangle',
  'Statement Ring',
  'Signet Ring',
  'Crystal Bracelet',
  'Layered Jewelry Set'
];

const WOMEN_SIZES = ['XS', 'S', 'M', 'L', 'XL'];
const WOMEN_COLORS = ['Black', 'Ivory', 'Beige', 'Olive', 'Navy', 'Burgundy'];
const JEWELRY_COLORS = ['Gold', 'Silver', 'Rose Gold'];

const out: string[] = [];
out.push('-- 0013_demo_categories_seed.sql');
out.push('-- Generated by scripts/generate-categories-seed.ts');
out.push('');
out.push('BEGIN;');
out.push('');

let productCount = 0;
let variantCount = 0;
let imageCount = 0;

function generateProducts(names: string[], categoryId: string, sizes: string[], colors: string[]) {
  for (const name of names) {
    productCount++;
    const id = uuid();
    const slug = faker.helpers.slugify(name).toLowerCase() + '-' + faker.string.alphanumeric(4);
    const price = faker.number.int({ min: 500000, max: 5000000 }); // 5k to 50k KES
    
    out.push(`insert into public.products (id, slug, name, short_description, full_description, category_id, price_cents, compare_at_price_cents, currency, care_instructions, fit_notes, meta_title, meta_description, is_featured, is_active, published_at) values (${escapeSql(id)}, ${escapeSql(slug)}, ${escapeSql(name)}, ${escapeSql(faker.commerce.productDescription())}, ${escapeSql(faker.lorem.paragraphs(2))}, ${escapeSql(categoryId)}, ${price}, NULL, 'KES', 'Dry clean only.', 'True to size.', ${escapeSql(name)}, ${escapeSql(`Shop ${name}`)}, ${faker.datatype.boolean()}, true, now()) on conflict (slug) do nothing;`);

    // Assign to collection
    out.push(`insert into public.product_collections (product_id, collection_id) values (${escapeSql(id)}, ${escapeSql(COLLECTION_ID)}) on conflict do nothing;`);

    // Images
    for (let i = 0; i < 3; i++) {
      imageCount++;
      const imageId = uuid();
      const isCover = i === 0;
      const url = `https://images.unsplash.com/photo-${faker.number.int({ min: 1000000000000, max: 9999999999999 })}?w=1200&q=80`;
      out.push(`insert into public.product_images (id, product_id, storage_path, display_order, is_cover) values (${escapeSql(imageId)}, ${escapeSql(id)}, ${escapeSql(url)}, ${i}, ${isCover}) on conflict do nothing;`);
    }

    // Variants
    const productColors = faker.helpers.arrayElements(colors, faker.number.int({ min: 1, max: 3 }));
    for (const color of productColors) {
      if (sizes.length > 0) {
        for (const size of sizes) {
          variantCount++;
          const varId = uuid();
          const sku = `${slug.substring(0, 8).toUpperCase()}-${color.substring(0,3).toUpperCase()}-${size}`;
          const stock = faker.number.int({ min: 0, max: 20 });
          out.push(`insert into public.product_variants (id, product_id, sku, size, color, stock_quantity, reserved_quantity, low_stock_threshold, barcode) values (${escapeSql(varId)}, ${escapeSql(id)}, ${escapeSql(sku)}, ${escapeSql(size)}, ${escapeSql(color)}, ${stock}, 0, 3, ${escapeSql(faker.string.numeric(12))}) on conflict (sku) do nothing;`);
        }
      } else {
        variantCount++;
        const varId = uuid();
        const sku = `${slug.substring(0, 8).toUpperCase()}-${color.substring(0,3).toUpperCase()}-OS`;
        const stock = faker.number.int({ min: 0, max: 20 });
        out.push(`insert into public.product_variants (id, product_id, sku, size, color, stock_quantity, reserved_quantity, low_stock_threshold, barcode) values (${escapeSql(varId)}, ${escapeSql(id)}, ${escapeSql(sku)}, NULL, ${escapeSql(color)}, ${stock}, 0, 3, ${escapeSql(faker.string.numeric(12))}) on conflict (sku) do nothing;`);
      }
    }
  }
}

generateProducts(womenswearNames, WOMENSWEAR_ID, WOMEN_SIZES, WOMEN_COLORS);
generateProducts(jewelryNames, JEWELRY_ID, [], JEWELRY_COLORS); // No sizes for jewelry

out.push('');
out.push('COMMIT;');

const outputPath = path.join(process.cwd(), 'supabase', 'migrations', '0013_demo_categories_seed.sql');
fs.writeFileSync(outputPath, out.join('\n'));

console.log(`Generated ${productCount} products, ${variantCount} variants, and ${imageCount} images.`);
console.log(`Wrote to ${outputPath}`);
