import { faker } from '@faker-js/faker';
import * as fs from 'fs';
import * as path from 'path';

faker.seed(42);

const SQL_FILE_PATH = path.join(__dirname, '..', 'supabase', 'migrations', '0012_demo_seed.sql');
let sql = `-- 0012_demo_seed.sql
-- Comprehensive realistic seed for Fashion & Co.
-- Generated by scripts/generate-seed.ts

BEGIN;

delete from public.categories cascade;
delete from public.collections cascade;
delete from auth.users cascade;

`;

function append(query: string) {
  sql += query + '\n';
}

function escapeSql(str: string | null | undefined) {
  if (str == null) return 'NULL';
  return `'${String(str).replace(/'/g, "''")}'`;
}

// Data Arrays for realism
const clothingAdjectives = ['Silk', 'Linen', 'Cotton', 'Merino', 'Cashmere', 'Ribbed', 'Pleated', 'Oversized', 'Tailored', 'Bias-cut', 'Wrap', 'Draped'];
const clothingNouns = ['Midi Dress', 'Blouse', 'Trousers', 'Maxi Dress', 'Slip Dress', 'Cardigan', 'Blazer', 'Skirt', 'Camisole', 'Turtleneck', 'Trench Coat'];
const clothingColors = ['Black', 'Ivory', 'Navy', 'Olive', 'Terracotta', 'Cocoa', 'Stone', 'Camel', 'Crimson'];
const clothingSizes = ['XS', 'S', 'M', 'L', 'XL'];

const jewelryAdjectives = ['Hammered', 'Textured', 'Minimal', 'Chunky', 'Delicate', 'Woven', 'Twisted', 'Sculptural'];
const jewelryNouns = ['Hoops', 'Studs', 'Chain Necklace', 'Pendant', 'Cuff', 'Bangle', 'Signet Ring', 'Stacking Ring', 'Drop Earrings'];
const jewelryMetals = ['14k Gold', '18k Gold Vermeil', 'Sterling Silver', 'Recycled Brass'];

const fashionImages = [
  'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=1200&q=80',
  'https://images.unsplash.com/photo-1550614000-4b95d4ed6032?w=1200&q=80',
  'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=1200&q=80',
  'https://images.unsplash.com/photo-1581044777550-4cfa60707c03?w=1200&q=80',
  'https://images.unsplash.com/photo-1509631179647-0c37cb1700ee?w=1200&q=80',
  'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=1200&q=80',
  'https://images.unsplash.com/photo-1487222477894-8943e31ef7b2?w=1200&q=80',
  'https://images.unsplash.com/photo-1566207274740-0f8cf6b7d5a5?w=1200&q=80',
];

const jewelryImages = [
  'https://images.unsplash.com/photo-1599643478524-fb524b0d0f72?w=1200&q=80',
  'https://images.unsplash.com/photo-1611085583191-a3b181a88401?w=1200&q=80',
  'https://images.unsplash.com/photo-1601121141461-9d6647bca1ed?w=1200&q=80',
  'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=1200&q=80',
  'https://images.unsplash.com/photo-1574015974293-817f0ebebb74?w=1200&q=80',
  'https://images.unsplash.com/photo-1596944924616-7b38e7cfac36?w=1200&q=80',
  'https://images.unsplash.com/photo-1629224316810-9d8805b95e76?w=1200&q=80',
];

function generateUsers() {
  append(`-- Users, Profiles, Roles, Addresses`);
  const users = [
    { id: faker.string.uuid(), email: 'admin@fashionandco.com', role: 'admin', name: 'Admin User' },
    { id: faker.string.uuid(), email: 'staff@fashionandco.com', role: 'staff', name: 'Staff User' },
    { id: faker.string.uuid(), email: 'vip@example.com', role: 'customer', name: 'VIP Customer' },
    { id: faker.string.uuid(), email: 'customer@example.com', role: 'customer', name: 'Regular Customer' },
  ];

  for (const u of users) {
    append(`insert into auth.users (id, instance_id, email, encrypted_password, email_confirmed_at, raw_app_meta_data, raw_user_meta_data, created_at, updated_at) values ('${u.id}', '00000000-0000-0000-0000-000000000000', '${u.email}', extensions.crypt('password123', extensions.gen_salt('bf')), now(), '{"provider":"email","providers":["email"]}', '{}', now(), now()) on conflict (id) do nothing;`);
    append(`insert into public.profiles (id, email, full_name, created_at, updated_at) values ('${u.id}', '${u.email}', '${u.name}', now(), now()) on conflict (id) do update set full_name = excluded.full_name;`);
    append(`insert into public.user_roles (user_id, role) values ('${u.id}', '${u.role}') on conflict (user_id) do update set role = excluded.role;`);
    if (u.role === 'customer') {
      append(`insert into public.addresses (id, user_id, label, recipient_name, phone, line1, city, country, is_default_shipping, is_default_billing) values ('${faker.string.uuid()}', '${u.id}', 'Home', '${u.name}', '${faker.phone.number()}', ${escapeSql(faker.location.streetAddress())}, 'Nairobi', 'KE', true, true) on conflict do nothing;`);
    }
  }
  return users;
}

function generateCategories() {
  append(`\n-- Categories`);
  const cats = [
    { id: faker.string.uuid(), name: 'Womenswear', slug: 'womenswear', parent: null, type: 'fashion' },
    { id: faker.string.uuid(), name: 'Jewelry', slug: 'jewelry', parent: null, type: 'jewelry' },
  ];
  const subcats = [
    { id: faker.string.uuid(), name: 'Dresses', slug: 'dresses', parent: 'womenswear', type: 'fashion' },
    { id: faker.string.uuid(), name: 'Tops', slug: 'tops', parent: 'womenswear', type: 'fashion' },
    { id: faker.string.uuid(), name: 'Outerwear', slug: 'outerwear', parent: 'womenswear', type: 'fashion' },
    { id: faker.string.uuid(), name: 'Necklaces', slug: 'necklaces', parent: 'jewelry', type: 'jewelry' },
    { id: faker.string.uuid(), name: 'Earrings', slug: 'earrings', parent: 'jewelry', type: 'jewelry' },
    { id: faker.string.uuid(), name: 'Rings', slug: 'rings', parent: 'jewelry', type: 'jewelry' },
  ];
  
  const all = [...cats, ...subcats];
  all.forEach((c, i) => {
    const pId = c.parent ? `'${all.find(x => x.slug === c.parent)!.id}'` : 'NULL';
    append(`insert into public.categories (id, name, slug, description, parent_id, display_order, meta_title, meta_description, is_active) values ('${c.id}', ${escapeSql(c.name)}, '${c.slug}', 'Shop premium ${c.name}.', ${pId}, ${i}, '${c.name} | Fashion & Co.', 'Discover ${c.name}.', true) on conflict (slug) do nothing;`);
  });
  return all;
}

function generateCollections() {
  append(`\n-- Collections`);
  const colls = [
    { id: faker.string.uuid(), name: 'The Nairobi Edit', slug: 'the-nairobi-edit', hero: fashionImages[0], featured: true },
    { id: faker.string.uuid(), name: 'Golden Hour', slug: 'golden-hour', hero: jewelryImages[0], featured: true },
    { id: faker.string.uuid(), name: 'Weekend Muse', slug: 'weekend-muse', hero: fashionImages[1], featured: false },
    { id: faker.string.uuid(), name: 'Minimal Gold', slug: 'minimal-gold', hero: jewelryImages[1], featured: true },
  ];
  colls.forEach(c => {
    append(`insert into public.collections (id, name, slug, subtitle, description, hero_image_url, is_featured, meta_title, meta_description, is_active) values ('${c.id}', ${escapeSql(c.name)}, '${c.slug}', 'Exclusive Capsule', 'A curated selection.', '${c.hero}', ${c.featured}, '${c.name} Collection', 'Shop ${c.name}.', true) on conflict (slug) do nothing;`);
  });
  return colls;
}

function generateProducts(categories: any[], collections: any[]) {
  append(`\n-- Products, Variants, Images, Collections`);
  
  const fashionCats = categories.filter(c => c.type === 'fashion' && c.parent);
  const jewelryCats = categories.filter(c => c.type === 'jewelry' && c.parent);

  for (let i = 0; i < 90; i++) {
    const isFashion = i < 60;
    const typeCats = isFashion ? fashionCats : jewelryCats;
    const cat = faker.helpers.arrayElement(typeCats);
    
    const adj = faker.helpers.arrayElement(isFashion ? clothingAdjectives : jewelryAdjectives);
    const noun = faker.helpers.arrayElement(isFashion ? clothingNouns : jewelryNouns);
    const name = `${adj} ${noun}`;
    const slug = faker.helpers.slugify(name).toLowerCase() + '-' + faker.string.alphanumeric(4);
    const priceCents = faker.number.int({ min: 500000, max: 4500000 }); // 5k - 45k KES
    const pId = faker.string.uuid();
    
    append(`insert into public.products (id, slug, name, short_description, full_description, category_id, price_cents, compare_at_price_cents, currency, care_instructions, fit_notes, meta_title, meta_description, is_featured, is_active, published_at) values ('${pId}', '${slug}', ${escapeSql(name)}, ${escapeSql(faker.commerce.productDescription())}, ${escapeSql(faker.lorem.paragraphs(2))}, '${cat.id}', ${priceCents}, NULL, 'KES', 'Dry clean only.', 'True to size.', ${escapeSql(name)}, ${escapeSql(`Shop ${name}`)}, ${faker.datatype.boolean()}, true, now()) on conflict (slug) do nothing;`);
    
    // Images
    const imgPool = isFashion ? fashionImages : jewelryImages;
    const numImages = faker.number.int({ min: 2, max: 4 });
    const selectedImgs = faker.helpers.arrayElements(imgPool, numImages);
    selectedImgs.forEach((url, idx) => {
      append(`insert into public.product_images (id, product_id, storage_path, display_order, is_cover) values ('${faker.string.uuid()}', '${pId}', '${url}', ${idx}, ${idx === 0}) on conflict do nothing;`);
    });
    
    // Variants
    if (isFashion) {
      const selectedColors = faker.helpers.arrayElements(clothingColors, faker.number.int({ min: 1, max: 3 }));
      selectedColors.forEach(color => {
        clothingSizes.forEach((size, sIdx) => {
          const vId = faker.string.uuid();
          const sku = `${slug.substring(0, 10)}-${color.substring(0, 3)}-${size}`.toUpperCase();
          const stock = faker.number.int({ min: 0, max: 20 });
          append(`insert into public.product_variants (id, product_id, sku, size, color, stock_quantity, reserved_quantity, low_stock_threshold, barcode) values ('${vId}', '${pId}', '${sku}', '${size}', '${color}', ${stock}, 0, 3, '${faker.string.numeric(12)}') on conflict (sku) do nothing;`);
        });
      });
    } else {
      const metal = faker.helpers.arrayElement(jewelryMetals);
      const vId = faker.string.uuid();
      const sku = `${slug.substring(0, 10)}-${metal.substring(0, 3)}`.toUpperCase();
      const stock = faker.number.int({ min: 5, max: 50 });
      append(`insert into public.product_variants (id, product_id, sku, metal, stock_quantity, reserved_quantity, low_stock_threshold, barcode) values ('${vId}', '${pId}', '${sku}', '${metal}', ${stock}, 0, 5, '${faker.string.numeric(12)}') on conflict (sku) do nothing;`);
    }

    // Collections mapping
    if (faker.datatype.boolean()) {
      const coll = faker.helpers.arrayElement(collections);
      append(`insert into public.product_collections (product_id, collection_id) values ('${pId}', '${coll.id}') on conflict do nothing;`);
    }
  }
}

function generateHomepage() {
  append(`\n-- Homepage Sections`);
  const sections = [
    { kind: 'hero', slug: 'main-hero', title: 'The Nairobi Edit', subtitle: 'Spring 2026 Collection', body: 'Discover our latest capsule.', cta_label: 'Shop Now', cta_href: '/collections/the-nairobi-edit', image_url: fashionImages[0] },
    { kind: 'editorial', slug: 'about-us', title: 'Our Story', subtitle: 'Crafted in Kenya', body: 'Premium materials, ethical production.', cta_label: 'Read More', cta_href: '/about', image_url: fashionImages[1] },
  ];
  sections.forEach((s, i) => {
    append(`insert into public.homepage_sections (id, kind, slug, title, subtitle, body, cta_label, cta_href, image_url, display_order, is_active) values ('${faker.string.uuid()}', '${s.kind}', '${s.slug}', ${escapeSql(s.title)}, ${escapeSql(s.subtitle)}, ${escapeSql(s.body)}, '${s.cta_label}', '${s.cta_href}', '${s.image_url}', ${i}, true) on conflict (slug) do update set title=excluded.title;`);
  });
}

function generateDiscountsDelivery() {
  append(`\n-- Discounts and Delivery`);
  append(`insert into public.delivery_zones (id, name, country, is_active) values ('00000000-0000-0000-0000-000000000001', 'Nairobi', 'KE', true) on conflict do nothing;`);
  append(`insert into public.delivery_rates (id, zone_id, name, price_cents, free_threshold_cents, is_active) values ('00000000-0000-0000-0000-000000000002', '00000000-0000-0000-0000-000000000001', 'Standard Delivery', 50000, 1500000, true) on conflict do nothing;`);
  
  const codes = [
    { code: 'WELCOME10', kind: 'percentage', val: 1000 }, // 10%
    { code: 'FREESHIP', kind: 'fixed_amount', val: 50000 },
    { code: 'NEW20', kind: 'percentage', val: 2000 },
  ];
  codes.forEach(c => {
    append(`insert into public.discount_codes (id, code, description, kind, applies_to, value, is_active) values ('${faker.string.uuid()}', '${c.code}', 'Promo', '${c.kind}', 'order', ${c.val}, true) on conflict (code) do nothing;`);
  });
}

async function main() {
  const users = generateUsers();
  const cats = generateCategories();
  const colls = generateCollections();
  generateProducts(cats, colls);
  generateHomepage();
  generateDiscountsDelivery();
  
  append(`\nCOMMIT;`);
  fs.writeFileSync(SQL_FILE_PATH, sql);
  console.log('Seed generated at:', SQL_FILE_PATH);
}

main().catch(console.error);
